### ISSUE TITLE
Regal's map icons are broken

### ISSUE THREAD

**Issue by BockyBlock** [balt-dev/robot-is-chill#150]
Run the command `=search source:regal-sprites icon_ type:tile` and try to place any of those tiles
It doesn't work because the bot searches in the Baba folder
![image](https://github.com/balt-dev/robot-is-chill/assets/97856812/d3e28513-53e4-4171-adcf-9bd462d20fbf)

**Comment by balt-dev** [comment]
fixed on other branch
