### ISSUE TITLE
text n39's name was changed without changing any other N texts

### ISSUE THREAD

**Issue by BockyBlock** [balt-dev/robot-is-chill#166]
It was changed from being an alternate version of "link" to simply a "ZLeda" word, while the sprite itself was moved to text_link4
You'd think this is on purpose, but none of the other N texts' names were changed, despite there being nothing different about them compared to N 39

**Comment by FofoFromBaba** [comment]
yeah it seems balt just changed the name of the text without moving it to a different source or anything

**Comment by Mathman2028** [comment]
from what i can tell balt just didnt like this one making sense

**Comment by Mathman2028** [comment]
after making the change he said "make a new n39" iirc

**Comment by BockyBlock** [comment]
why didn't they change jqzy, qff, savor, or redo???

**Comment by Mathman2028** [comment]
alternatively he thought it would be funny to have 4 links

**Comment by balt-dev** [comment]
yeah the last one, i thought it'd be funny to have a lot of links

**Comment by Mathman2028** [comment]
so is this gonna be closed or
