### ISSUE TITLE
patrick sprite

### ISSUE THREAD

**Issue by jawa-08** [balt-dev/robot-is-chill#66]
i dont know if this is intended, but the patrick sprite for up sleep is blinking instead of sleeping

**Comment by RaidoCat** [comment]
He just has insomnia when he looks up

**Comment by balt-is-you-and-shift** [comment]
hhhh sorry

**Comment by krovellium** [comment]
who is Patrick

**Comment by prismacrafter** [comment]
from the hit game patrick's parabox

**Comment by krovellium** [comment]
Real

**Comment by CenTdemeern1** [comment]
@balt-dev bump

**Comment by krovellium** [comment]
Why you gotta do me like that 
Also isn’t this issue fixed, just close it

**Comment by CenTdemeern1** [comment]
> Why you gotta do me like that

If you mean marking your comments as off topic, I marked them correctly.

> Also isn’t this issue fixed, just close it

No, the issue is not fixed

**Comment by krovellium** [comment]
Isn't it just a simple sprite reference issue (i'm assuming the sprite already exists just hasn't been correctly assigned)?

if so, its been almost 6 months to fix a single line of code
also "who is patrick" isn't off topic

**Comment by balt-dev** [comment]
I forgot about this for like 6 months oops

**Comment by balt-dev** [comment]
fixed in https://github.com/balt-dev/robot-is-chill/commit/42df6e5668d0304d0f97717fe530158f78e8033e

**Comment by krovellium** [comment]
> fixed in [42df6e5](https://github.com/balt-dev/robot-is-chill/commit/42df6e5668d0304d0f97717fe530158f78e8033e)
Thank you Balt

**Comment by CenTdemeern1** [comment]
> also "who is patrick" isn't off topic 

By GitHub standards it is. You don't get to decide that.
